# ESTADISTICA APLICADA

## CLASE 26 DE ENERO 2023 GRUPO 043

## SESIÓN 2
## ANDRIK DANIEL VAZQUEZ REGALADO

In [59]:
!pip install yfinance

In [60]:
import yfinance as yf

In [2]:
import numpy as np

In [3]:
edades = [12, 18, 25, 32, 40]

In [4]:
type(edades)

list

In [5]:
np.array(edades)

array([12, 18, 25, 32, 40])

In [6]:
edades=np.array(edades)

In [7]:
type(edades)

numpy.ndarray

In [8]:
np.mean(edades) #Calcula el promedio

25.4

In [9]:
np.prod(edades) #multiplica todas las edades

6912000

In [11]:
np.var(edades) #Se calcula la varianza poblacional

98.24000000000001

In [17]:
np.var(edades,ddof=1) #Varianza muestral

122.80000000000001

In [18]:
np.std(edades) #Desv estandar poblacional

9.911609354691095

In [19]:
np.std(edades, ddof=1) #Desv estandar muestral

11.081516141756055

In [20]:
np.arange(9) #Genera un vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.arange(1,9) #Inicio y finalizacion del vector

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.arange(1,100,10) #un vector con salto

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.full(6,9)

array([9, 9, 9, 9, 9, 9])

In [33]:
np.random.seed(15)
np.random.randint(0,25,10) #numero aleatorios enteros, primero el rango y despues la cantidad

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [39]:
np.random.seed(15)
aleatorios = np.random.randint(0,25,10)

In [40]:
aleatorios

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [41]:
aleatorios = np.sort(aleatorios)

In [42]:
aleatorios

array([ 0,  5,  7,  8, 11, 12, 21, 21, 22, 23])

In [43]:
aleatorios[3]

8

In [44]:
aleatorios[[3,5]]

array([ 8, 12])

In [45]:
aleatorios>5

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [46]:
aleatorios[aleatorios>5]

array([ 7,  8, 11, 12, 21, 21, 22, 23])

## Metodos - Si ya creaste el objeto y llamaste libreria

In [47]:
numeros=[1.23, 2.45578, 5.6888785]
numeros= np.array(numeros)

# funcion

In [48]:
np.mean(numeros)

3.1248861666666667

# metodo

In [49]:
numeros.mean()

3.1248861666666667

In [53]:
round(np.mean(np.array(numeros)),2) #funcion

3.12

In [54]:
np.array(numeros).mean().round(2) #metodo

3.12